# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MPC_qr <- function(nn, data, theta_boot, data_boot, alpha, M_samp, B_resamp) {
    .Call('MPC_MPC_qr', PACKAGE = 'MPC', nn, data, theta_boot, data_boot, alpha, M_samp, B_resamp)
}

MPC_linreg <- function(nn, data, theta_boot, data_boot, alpha, M_samp, B_resamp) {
    .Call('MPC_MPC_linreg', PACKAGE = 'MPC', nn, data, theta_boot, data_boot, alpha, M_samp, B_resamp)
}

MPC_varmix <- function(nn, data, data_boot, alpha, B_resamp) {
    .Call('MPC_MPC_varmix', PACKAGE = 'MPC', nn, data, data_boot, alpha, B_resamp)
}