# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GPC_qr <- function(nn, data, theta_boot, data_boot, alpha, M_samp, B_resamp) {
    .Call('GPC_GPC_qr', PACKAGE = 'GPC', nn, data, theta_boot, data_boot, alpha, M_samp, B_resamp)
}

GPC_linreg <- function(nn, data, theta_boot, data_boot, alpha, M_samp, B_resamp) {
    .Call('GPC_GPC_linreg', PACKAGE = 'GPC', nn, data, theta_boot, data_boot, alpha, M_samp, B_resamp)
}

GPC_varmix <- function(nn, data, data_boot, alpha, B_resamp) {
    .Call('GPC_GPC_varmix', PACKAGE = 'GPC', nn, data, data_boot, alpha, B_resamp)
}